package com.proteam.renew.requestModels

data class OnBoarding(
    val aadhaar_card: String = "",
    val aadhaar_no: String = "",
    val address_line_1: String = "",
    val blood_group: String = "",
    val city: String = "",
    val dob: String = "",
    val doj: String = "",
    val driving_license_no: String = "",
    val driving_lisence_docs: String = "" ,
    val driving_license_expiry_date: String = "",
    val emergency_contact_name: String = "",
    val emergency_contact_no: String = "",
    val employer_contractor_name: String = "",
    val exp_month: String = "",
    val exp_year: String = "",
    val father_name: String = "",
    val full_name: String = "",
    val gender: String = "",
    val induction_date: String = "",
    val induction_status: String = "",
    val medical_certificate: String = "",
    val medical_test_date: String = "",
    val medical_test_status: String = "",
    val mobile_no: String = "",
    val nationality: String = "",
    val pin_code: String = "",
    val profilepic: String = "",
    val project: String = "",
    val skill_set: String = "",
    val skill_type: String = "",
    val state: String = "",
    val subcontract_contract_no: String = "",
    val subcontractor_name: String = "",
    val user_id: String = "",
    val work_employee_designation: String= ""
)